---
openapi: 3.0.1
info:
  title: SMSApi
  version: v1
paths:
  "/Sms":
    post:
      summary: Enviar un mensaje
      tags:
      - Sms
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SendSMSRequest"
          text/json:
            schema:
              "$ref": "#/components/schemas/SendSMSRequest"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/SendSMSRequest"
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                "$ref": "#/components/schemas/SendSMSResponse"
            application/json:
              schema:
                "$ref": "#/components/schemas/SendSMSResponse"
            text/json:
              schema:
                "$ref": "#/components/schemas/SendSMSResponse"
  "/Sms/file":
    post:
      summary: Enviar un archivo
      tags:
      - Sms
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SingleSendFileRequest"
          text/json:
            schema:
              "$ref": "#/components/schemas/SingleSendFileRequest"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/SingleSendFileRequest"
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                "$ref": "#/components/schemas/SingleSmsFileResponse"
            application/json:
              schema:
                "$ref": "#/components/schemas/SingleSmsFileResponse"
            text/json:
              schema:
                "$ref": "#/components/schemas/SingleSmsFileResponse"  
components:
  schemas:
    SendSMSRequest:
      required:
      - celular
      - clientKey
      - mensaje
      - referencia
      type: object
      properties:
        clientKey:
          minLength: 1
          type: string
          description: Su API Key
        celular:
          minLength: 1
          type: string
          description: Número de celular
        mensaje:
          minLength: 1
          type: string
          description: Mensaje a enviar
        referencia:
          minLength: 1
          type: string
      additionalProperties: false
    SendSMSResponse:
      type: object
      properties:
        mensajeId:
          type: string
          nullable: false
        resultado:
          type: string
          nullable: false
      additionalProperties: false
    SingleSendFileRequest:
      type: object
      properties:
        clientKey:
          type: string
          nullable: false
          description: Su API Key
        celular:
          type: string
          nullable: false
          description: Número de celular
        mensaje:
          type: string
          nullable: false
          description: Mensaje a enviar
        contenido:
          type: string
          format: byte
          nullable: false
          description: Contenido del archivo en BASE-64 Encoding
      additionalProperties: false
    SingleSmsFileResponse:
      type: object
      properties:
        jobId:
          type: string
          nullable: false
          description: Número de trabajo asignado para su referencia
        envioId:
          type: integer
          format: int64
          description: ID de envío asignado para su referencia
      additionalProperties: false
